print "mhello git"
print "mhello git"
print "mhello git"
print "mhello git"
print "mhello git"
print "hello git"
print "hello git"
print "hello git"
print "git  checkout me before add is null"
print "git  checkout me after add or commit is ok"
print "git  checkout HEAD me is come back from repository and overwrite working area and buffer cache"
print "git branch name; git checkout name    ==  git checkout -b name"
print "master change first.than branch change"
